runtime: custom
env: flex
#entrypoint: gunicorn -t 2400 -b :$PORT main:app
entrypoint: gunicorn -b :$PORT main:server

# runtime_config:
#   python_version: 3

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 0.5
  memory_gb: 0.18
  disk_size_gb: 10
